'use client';

import { useState, useRef } from 'react';
import { useApp } from '@/context/AppContext';
import { generateDoctorReport } from '@/services/gemini';
import { markdownToSafeHTML, markdownToDownloadHTML } from '@/lib/sanitize';
import { FileText, Loader2, Download, RefreshCw, Printer, Sparkles } from 'lucide-react';
import Link from 'next/link';

export default function ReportPage() {
  const { meals, insights, bloodWork, isLoading } = useApp();
  const [report, setReport] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const reportRef = useRef<HTMLDivElement>(null);

  const handleGenerate = async () => {
    if (meals.length === 0) return;
    
    setIsGenerating(true);
    setError(null);
    
    try {
      const generatedReport = await generateDoctorReport(
        meals,
        insights,
        bloodWork || undefined
      );
      setReport(generatedReport);
    } catch (err) {
      console.error('Report generation error:', err);
      setError('Failed to generate report. Please check your API key and try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    if (!report) return;
    
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Dietary Pattern Report</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.7;
      color: #1c1917;
      max-width: 800px;
      margin: 0 auto;
      padding: 48px;
    }
    h1 { color: #1c1917; font-size: 28px; border-bottom: 2px solid #e7e5e4; padding-bottom: 16px; margin-bottom: 24px; }
    h2 { color: #44403c; font-size: 20px; margin-top: 32px; margin-bottom: 16px; }
    h3 { color: #57534e; font-size: 16px; }
    ul { padding-left: 24px; }
    li { margin-bottom: 8px; }
    .header { margin-bottom: 32px; }
    .meta { color: #78716c; font-size: 14px; margin-bottom: 4px; }
    .stats { display: flex; gap: 24px; margin: 24px 0; padding: 20px; background: #fafaf9; border-radius: 12px; }
    .stat { text-align: center; }
    .stat-value { font-size: 28px; font-weight: 600; }
    .stat-label { font-size: 12px; color: #78716c; }
    .footer { 
      margin-top: 48px; 
      padding-top: 24px; 
      border-top: 1px solid #e7e5e4;
      font-size: 12px; 
      color: #78716c; 
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Dietary Pattern Report</h1>
    <p class="meta">Generated: ${new Date().toLocaleDateString()}</p>
    <p class="meta">Period: ${insights.dateRange}</p>
    <p class="meta">Meals Analyzed: ${insights.totalMeals}</p>
  </div>
  
  <div class="stats">
    <div class="stat">
      <div class="stat-value" style="color: #d97706;">${insights.plastic.count}</div>
      <div class="stat-label">Plastic Bottles</div>
    </div>
    <div class="stat">
      <div class="stat-value" style="color: #dc2626;">${insights.processedMeat.perWeek.toFixed(1)}/wk</div>
      <div class="stat-label">Processed Meat</div>
    </div>
    <div class="stat">
      <div class="stat-value" style="color: #7c3aed;">${insights.mealTiming.lateMealPercent}%</div>
      <div class="stat-label">Late Meals</div>
    </div>
  </div>
  
  ${markdownToDownloadHTML(report)}
  
  <div class="footer">
    <p>This report was generated from patient-logged dietary data and AI pattern analysis.</p>
    <p>It is intended as a reference tool for clinical discussion, not a diagnosis.</p>
    <p><strong>Generated by:</strong> Dietary Black Box</p>
  </div>
</body>
</html>`;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `dietary-report-${new Date().toISOString().split('T')[0]}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (isLoading) {
    return (
      <div className="min-h-[80vh] flex items-center justify-center">
        <div className="flex items-center gap-3 text-warm-500">
          <div className="w-5 h-5 border-2 border-warm-300 border-t-warm-600 rounded-full animate-spin" />
          <span>Loading...</span>
        </div>
      </div>
    );
  }

  if (meals.length === 0) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-8">
        <h1 className="text-display text-3xl text-warm-900 mb-2">Doctor Report</h1>
        <p className="text-warm-500 mb-8">AI-generated report for your physician</p>
        
        <div className="card-elevated text-center py-16">
          <div className="w-16 h-16 rounded-2xl bg-warm-100 flex items-center justify-center mx-auto mb-4">
            <FileText className="w-8 h-8 text-warm-400" />
          </div>
          <h3 className="text-lg font-semibold text-warm-800 mb-2">No meal data available</h3>
          <p className="text-warm-500 mb-6">Log some meals to generate a report</p>
          <Link href="/app/capture" className="btn btn-primary">
            Log Your First Meal
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      <div className="flex items-center justify-between mb-10">
        <div>
          <h1 className="text-display text-3xl text-warm-900 mb-2">Doctor Report</h1>
          <p className="text-warm-500">AI-generated report for your physician</p>
        </div>
        
        {report && (
          <div className="flex items-center gap-2">
            <button
              onClick={handleGenerate}
              className="btn btn-secondary btn-sm"
              disabled={isGenerating}
            >
              <RefreshCw className={`w-4 h-4 ${isGenerating ? 'animate-spin' : ''}`} />
              Regenerate
            </button>
            <button
              onClick={handlePrint}
              className="btn btn-secondary btn-sm"
            >
              <Printer className="w-4 h-4" />
              Print
            </button>
            <button
              onClick={handleDownload}
              className="btn btn-primary btn-sm"
            >
              <Download className="w-4 h-4" />
              Download
            </button>
          </div>
        )}
      </div>

      {/* Summary Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
        <div className="card-elevated text-center py-4">
          <p className="text-display text-2xl text-warm-900">{insights.totalMeals}</p>
          <p className="text-xs text-warm-500">Meals</p>
        </div>
        <div className="card-elevated text-center py-4">
          <p className="text-display text-2xl text-amber-600">{insights.plastic.count}</p>
          <p className="text-xs text-warm-500">Plastic Bottles</p>
        </div>
        <div className="card-elevated text-center py-4">
          <p className="text-display text-2xl text-rose-600">{insights.processedMeat.perWeek.toFixed(1)}/wk</p>
          <p className="text-xs text-warm-500">Processed Meat</p>
        </div>
        <div className="card-elevated text-center py-4">
          <p className="text-display text-2xl text-violet-600">{insights.mealTiming.lateMealPercent}%</p>
          <p className="text-xs text-warm-500">Late Meals</p>
        </div>
      </div>

      {/* Blood Work Status */}
      {bloodWork ? (
        <div className="card-elevated bg-emerald-50 border-emerald-100 mb-8">
          <div className="flex items-center gap-2 text-emerald-700">
            <FileText className="w-5 h-5" />
            <span className="font-medium">Blood work from {bloodWork.testDate.toLocaleDateString()} will be included</span>
          </div>
        </div>
      ) : (
        <div className="card-elevated bg-amber-50 border-amber-100 mb-8">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2 text-amber-700">
              <FileText className="w-5 h-5" />
              <span className="font-medium">No blood work added yet</span>
            </div>
            <span className="text-sm text-amber-600">
              Blood work input coming soon
            </span>
          </div>
        </div>
      )}

      {error && (
        <div className="card-elevated bg-rose-50 border-rose-100 mb-8">
          <p className="text-rose-700">{error}</p>
        </div>
      )}

      {/* Generate Button or Report Display */}
      {!report ? (
        <div className="card-elevated text-center py-20">
          <div className="w-20 h-20 rounded-3xl bg-gradient-to-br from-warm-100 to-warm-200 flex items-center justify-center mx-auto mb-8">
            <Sparkles className="w-10 h-10 text-warm-500" />
          </div>
          <h3 className="text-xl font-semibold text-warm-800 mb-3">
            Ready to Generate Report
          </h3>
          <p className="text-warm-500 mb-8 max-w-md mx-auto">
            Our AI will analyze your meal patterns and create a professional 
            report suitable for sharing with your healthcare provider.
          </p>
          <button
            onClick={handleGenerate}
            disabled={isGenerating}
            className="btn btn-primary btn-lg"
          >
            {isGenerating ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin" />
                Generating Report...
              </>
            ) : (
              <>
                <FileText className="w-5 h-5" />
                Generate Doctor Report
              </>
            )}
          </button>
        </div>
      ) : (
        <div ref={reportRef} className="card-elevated print:shadow-none print:border-0">
          <div className="mb-8 pb-6 border-b border-warm-200">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 bg-warm-900 rounded-lg flex items-center justify-center">
                <FileText className="w-5 h-5 text-white" />
              </div>
              <div>
                <h2 className="text-xl font-semibold text-warm-900">Dietary Pattern Report</h2>
                <p className="text-sm text-warm-400">
                  Generated {new Date().toLocaleDateString()} • {insights.dateRange} • {insights.totalMeals} meals
                </p>
              </div>
            </div>
          </div>
          
          <div
            className="prose prose-warm max-w-none prose-headings:text-warm-800 prose-p:text-warm-600 prose-li:text-warm-600"
            dangerouslySetInnerHTML={{
              __html: markdownToSafeHTML(report)
            }}
          />
          
          <div className="mt-10 pt-6 border-t border-warm-200 text-xs text-warm-400">
            <p className="mb-2">
              This report was generated from patient-logged dietary data and AI pattern analysis. 
              It is intended as a reference tool for clinical discussion, not a diagnosis. 
              Dietary recommendations should be made by qualified healthcare providers.
            </p>
            <p>
              <strong>Report ID:</strong> RPT-{Date.now().toString(36).toUpperCase()} • 
              <strong> Generated by:</strong> Dietary Black Box
            </p>
          </div>
        </div>
      )}

      {/* Print styles */}
      <style jsx global>{`
        @media print {
          body * {
            visibility: hidden;
          }
          .print\\:shadow-none,
          .print\\:shadow-none * {
            visibility: visible;
          }
          .print\\:shadow-none {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
            padding: 40px;
          }
          nav, button, .btn {
            display: none !important;
          }
        }
      `}</style>
    </div>
  );
}

