import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  SafeAreaView,
  TouchableOpacity,
  ActivityIndicator,
  Alert
} from 'react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { getMeals } from '../services/meals';
import { calculateInsights } from '../services/insights';
import { generateDoctorReport } from '../services/gemini';

interface Props {
  navigation: any;
}

export default function ReportScreen({ navigation }: Props) {
  const [report, setReport] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    generateReport();
  }, []);

  const generateReport = async () => {
    try {
      const meals = await getMeals('demo_user');
      const insights = calculateInsights(meals);

      // Create meal summary
      const mealSummary = meals.slice(0, 20).map(m =>
        `${new Date(m.loggedAt).toLocaleDateString()}: ${m.foods.map(f => f.name).join(', ')}`
      ).join('\n');

      const reportText = await generateDoctorReport(
        mealSummary,
        {
          plasticCount: insights.plastic.count,
          plasticPerDay: insights.plastic.perDay,
          processedMeatCount: insights.processedMeat.count,
          processedMeatPerWeek: insights.processedMeat.perWeek,
          lateMealPercent: insights.mealTiming.lateMealPercent,
          avgDinnerTime: insights.mealTiming.avgDinnerTime,
          totalMeals: insights.totalMeals,
          dateRange: insights.dateRange,
        }
      );

      setReport(reportText);
    } catch (error) {
      console.error('Error generating report:', error);
      Alert.alert('Error', 'Failed to generate report. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const exportPDF = async () => {
    if (!report) return;

    setExporting(true);
    try {
      // Convert markdown to HTML
      const html = `
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                padding: 40px;
                line-height: 1.6;
                color: #1a1a1a;
              }
              h1 { color: #0D1117; border-bottom: 2px solid #238636; padding-bottom: 10px; }
              h2 { color: #21262D; margin-top: 24px; }
              h3 { color: #30363D; }
              ul { margin: 10px 0; }
              li { margin: 5px 0; }
              .footer {
                margin-top: 40px;
                padding-top: 20px;
                border-top: 1px solid #e1e4e8;
                font-size: 12px;
                color: #6a737d;
              }
            </style>
          </head>
          <body>
            ${report
              .replace(/^### (.*$)/gm, '<h3>$1</h3>')
              .replace(/^## (.*$)/gm, '<h2>$1</h2>')
              .replace(/^# (.*$)/gm, '<h1>$1</h1>')
              .replace(/^\* (.*$)/gm, '<li>$1</li>')
              .replace(/^\- (.*$)/gm, '<li>$1</li>')
              .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
              .replace(/\n\n/g, '</p><p>')
              .replace(/^(?!<[hlu])/gm, '<p>')
            }
            <div class="footer">
              <p>Generated by DataDiet - Your Dietary Black Box</p>
              <p>Powered by Gemini AI | ${new Date().toLocaleDateString()}</p>
              <p><em>This report is intended for clinical discussion, not diagnosis.</em></p>
            </div>
          </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html });
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: 'Share Doctor Report'
      });
    } catch (error) {
      console.error('Error exporting PDF:', error);
      Alert.alert('Error', 'Failed to export PDF. Please try again.');
    } finally {
      setExporting(false);
    }
  };

  if (loading) {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => navigation.goBack()}>
            <Text style={styles.backButton}>← Back</Text>
          </TouchableOpacity>
          <Text style={styles.title}>Doctor Report</Text>
        </View>
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="large" color="#4A90A4" />
          <Text style={styles.loadingText}>Generating report with AI...</Text>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()}>
          <Text style={styles.backButton}>← Back</Text>
        </TouchableOpacity>
        <Text style={styles.title}>Doctor Report</Text>
      </View>

      <ScrollView style={styles.scrollView} showsVerticalScrollIndicator={false}>
        <View style={styles.reportCard}>
          <Text style={styles.reportText}>{report}</Text>
        </View>
      </ScrollView>

      <View style={styles.footer}>
        <TouchableOpacity
          style={styles.exportButton}
          onPress={exportPDF}
          disabled={exporting}
        >
          {exporting ? (
            <ActivityIndicator color="#FFFFFF" />
          ) : (
            <Text style={styles.exportButtonText}>📤 Export & Share PDF</Text>
          )}
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0D1117',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    paddingTop: 10,
  },
  backButton: {
    color: '#58A6FF',
    fontSize: 16,
  },
  title: {
    fontSize: 20,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 20,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#8B949E',
  },
  scrollView: {
    flex: 1,
    padding: 20,
  },
  reportCard: {
    backgroundColor: '#161B22',
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: '#30363D',
  },
  reportText: {
    fontSize: 15,
    color: '#C9D1D9',
    lineHeight: 24,
  },
  footer: {
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#30363D',
  },
  exportButton: {
    backgroundColor: '#238636',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  exportButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
  },
});
