import React, { useState, useEffect, useCallback } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  Pressable,
  Alert,
} from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { useFocusEffect } from '@react-navigation/native';
import Animated, {
  useAnimatedStyle,
  interpolateColor,
} from 'react-native-reanimated';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import Icon from '../components/Icon';
import { useTheme, useAnimatedBackground } from '../context/ThemeContext';
import { haptics } from '../utils/haptics';
import { SPACING, TYPOGRAPHY, RADIUS, DARK, LIGHT } from '../config/designSystem';
import { Button } from '../components/Button';
import {
  getReportById,
  formatReportDate,
  SavedReport,
} from '../services/reportHistory';

interface Props {
  navigation: any;
  route: {
    params: {
      reportId: string;
    };
  };
}

export default function ReportDetailScreen({ navigation, route }: Props) {
  const { colors, themeProgress } = useTheme();
  const animatedBackground = useAnimatedBackground();
  const insets = useSafeAreaInsets();
  const [report, setReport] = useState<SavedReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [exporting, setExporting] = useState(false);
  const footerHeight = SPACING.xxl + SPACING.lg + 56;
  const scrollPaddingBottom = footerHeight + insets.bottom;

  const titleStyle = useAnimatedStyle(() => ({
    color: interpolateColor(
      themeProgress.value,
      [0, 1],
      [LIGHT.text, DARK.text]
    ),
  }));

  const subtitleStyle = useAnimatedStyle(() => ({
    color: interpolateColor(
      themeProgress.value,
      [0, 1],
      [LIGHT.textMuted, DARK.textMuted]
    ),
  }));

  useEffect(() => {
    loadReport();
  }, [route.params.reportId]);

  // Reset exporting state when screen gains focus (e.g., when returning from share dialog)
  useFocusEffect(
    useCallback(() => {
      setExporting(false);
    }, [])
  );

  const loadReport = async () => {
    try {
      const savedReport = await getReportById(route.params.reportId);
      setReport(savedReport);
    } catch (error) {
      console.error('Error loading report:', error);
      Alert.alert('Error', 'Failed to load report');
      navigation.goBack();
    } finally {
      setLoading(false);
    }
  };

  const exportPDF = async () => {
    if (!report) return;

    setExporting(true);
    haptics.light();

    try {
      const html = `
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                padding: 40px;
                line-height: 1.6;
                color: #1a1a1a;
              }
              h1 { color: #0F1419; border-bottom: 2px solid #13c8ec; padding-bottom: 10px; }
              h2 { color: #21262D; margin-top: 24px; }
              h3 { color: #30363D; }
              ul { margin: 10px 0; }
              li { margin: 5px 0; }
              .period { color: #13c8ec; font-weight: 600; }
              .footer {
                margin-top: 40px;
                padding-top: 20px;
                border-top: 1px solid #e1e4e8;
                font-size: 12px;
                color: #6a737d;
              }
            </style>
          </head>
          <body>
            <p class="period">Report Period: ${report.periodLabel} (${report.periodDays} days)</p>
            ${report.report
              .replace(/^### (.*$)/gm, '<h3>$1</h3>')
              .replace(/^## (.*$)/gm, '<h2>$1</h2>')
              .replace(/^# (.*$)/gm, '<h1>$1</h1>')
              .replace(/^\* (.*$)/gm, '<li>$1</li>')
              .replace(/^\- (.*$)/gm, '<li>$1</li>')
              .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
              .replace(/\n\n/g, '</p><p>')
              .replace(/^(?!<[hlu])/gm, '<p>')
            }
            <div class="footer">
              <p>Generated by DataDiet - Your Dietary Black Box</p>
              <p>Originally created: ${new Date(report.createdAt).toLocaleDateString()}</p>
              <p><em>This report is intended for clinical discussion, not diagnosis.</em></p>
            </div>
          </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html });
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: 'Share Doctor Report',
      });

      haptics.success();
    } catch (error) {
      console.error('Error exporting PDF:', error);
      haptics.error();
      Alert.alert('Error', 'Failed to export PDF. Please try again.');
    } finally {
      setExporting(false);
    }
  };

  if (loading || !report) {
    return (
      <Animated.View style={[styles.container, animatedBackground]}>
        <SafeAreaView style={styles.safe}>
          <View style={styles.loadingContainer}>
            <Animated.Text style={[styles.loadingText, subtitleStyle]}>
              Loading report...
            </Animated.Text>
          </View>
        </SafeAreaView>
      </Animated.View>
    );
  }

  return (
    <Animated.View style={[styles.container, animatedBackground]}>
      <SafeAreaView style={styles.safe} edges={['top']}>
        <View style={styles.header}>
          <Pressable
            onPress={() => {
              haptics.light();
              navigation.goBack();
            }}
            hitSlop={10}
            style={styles.backButton}
          >
            <Icon
              name="arrow-left"
              size={24}
              color={colors.text}
            />
          </Pressable>
          <View style={styles.headerText}>
            <Animated.Text style={[styles.title, titleStyle]}>
              {report.periodLabel} Report
            </Animated.Text>
            <Animated.Text style={[styles.subtitle, subtitleStyle]}>
              {formatReportDate(report.createdAt)} • {report.mealCount} meals
            </Animated.Text>
          </View>
        </View>

        <ScrollView
          style={styles.scrollView}
          contentContainerStyle={[styles.scrollContent, { paddingBottom: scrollPaddingBottom }]}
          showsVerticalScrollIndicator={false}
        >
          <ReportCard
            report={report}
            themeProgress={themeProgress}
            colors={colors}
          />
          <DisclaimerBox themeProgress={themeProgress} colors={colors} />
        </ScrollView>

        <FooterButton onExport={exportPDF} exporting={exporting} themeProgress={themeProgress} bottomInset={insets.bottom} />
      </SafeAreaView>
    </Animated.View>
  );
}

// Markdown renderer (same as in ReportScreen)
function MarkdownRenderer({ text, colors, themeProgress }: { text: string; colors: any; themeProgress: Animated.SharedValue<number> }) {
  const lines = text.split('\n');
  const elements: React.ReactNode[] = [];
  let keyIndex = 0;

  const getTextColor = () => colors.text;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) {
      elements.push(<View key={keyIndex++} style={{ height: 8 }} />);
      continue;
    }

    if (line.startsWith('# ')) {
      elements.push(
        <View key={keyIndex++} style={markdownStyles.h1Container}>
          <Text style={[markdownStyles.h1, { color: getTextColor() }]}>
            {line.substring(2)}
          </Text>
          <View style={[markdownStyles.h1Underline, { backgroundColor: colors.primary }]} />
        </View>
      );
      continue;
    }

    if (line.startsWith('## ')) {
      elements.push(
        <View key={keyIndex++} style={markdownStyles.h2Container}>
          <Text style={[markdownStyles.h2, { color: getTextColor() }]}>
            {line.substring(3)}
          </Text>
        </View>
      );
      continue;
    }

    if (line.startsWith('### ')) {
      elements.push(
        <Text key={keyIndex++} style={[markdownStyles.h3, { color: getTextColor() }]}>
          {line.substring(4)}
        </Text>
      );
      continue;
    }

    if (line.startsWith('- ') || line.startsWith('* ')) {
      const bulletText = line.substring(2);
      elements.push(
        <View key={keyIndex++} style={markdownStyles.bulletContainer}>
          <View style={[markdownStyles.bulletDot, { backgroundColor: colors.primary }]} />
          <Text style={[markdownStyles.bulletText, { color: getTextColor() }]}>
            {renderInlineFormatting(bulletText, colors)}
          </Text>
        </View>
      );
      continue;
    }

    elements.push(
      <Text key={keyIndex++} style={[markdownStyles.paragraph, { color: getTextColor() }]}>
        {renderInlineFormatting(line, colors)}
      </Text>
    );
  }

  return <View style={markdownStyles.container}>{elements}</View>;
}

function renderInlineFormatting(text: string, colors: any): React.ReactNode {
  const parts: React.ReactNode[] = [];
  let remaining = text;
  let keyIndex = 0;

  while (remaining.length > 0) {
    const boldMatch = remaining.match(/\*\*(.+?)\*\*/);
    if (boldMatch && boldMatch.index !== undefined) {
      if (boldMatch.index > 0) {
        parts.push(<Text key={keyIndex++}>{remaining.substring(0, boldMatch.index)}</Text>);
      }
      parts.push(
        <Text key={keyIndex++} style={{ fontFamily: TYPOGRAPHY.fontFamily.bold, color: colors.text }}>
          {boldMatch[1]}
        </Text>
      );
      remaining = remaining.substring(boldMatch.index + boldMatch[0].length);
    } else {
      parts.push(<Text key={keyIndex++}>{remaining}</Text>);
      break;
    }
  }

  return parts.length === 1 ? parts[0] : <>{parts}</>;
}

const markdownStyles = StyleSheet.create({
  container: { gap: 4 },
  h1Container: { marginTop: SPACING.lg, marginBottom: SPACING.md },
  h1: { fontFamily: TYPOGRAPHY.fontFamily.bold, fontSize: TYPOGRAPHY.sizes.headlineLarge, marginBottom: SPACING.xs },
  h1Underline: { height: 3, width: 40, borderRadius: 2 },
  h2Container: { marginTop: SPACING.lg, marginBottom: SPACING.sm, paddingBottom: SPACING.xs, borderBottomWidth: 1, borderBottomColor: 'rgba(128,128,128,0.2)' },
  h2: { fontFamily: TYPOGRAPHY.fontFamily.semiBold, fontSize: TYPOGRAPHY.sizes.headlineMedium },
  h3: { fontFamily: TYPOGRAPHY.fontFamily.semiBold, fontSize: TYPOGRAPHY.sizes.headlineSmall, marginTop: SPACING.md, marginBottom: SPACING.xs },
  bulletContainer: { flexDirection: 'row', alignItems: 'flex-start', marginVertical: SPACING.xs, paddingLeft: SPACING.sm },
  bulletDot: { width: 6, height: 6, borderRadius: 3, marginTop: 7, marginRight: SPACING.sm },
  bulletText: { flex: 1, fontFamily: TYPOGRAPHY.fontFamily.regular, fontSize: TYPOGRAPHY.sizes.bodyMedium, lineHeight: 22 },
  paragraph: { fontFamily: TYPOGRAPHY.fontFamily.regular, fontSize: TYPOGRAPHY.sizes.bodyMedium, lineHeight: 24, marginVertical: SPACING.xs },
});

interface ReportCardProps {
  report: SavedReport;
  themeProgress: Animated.SharedValue<number>;
  colors: any;
}

function ReportCard({ report, themeProgress, colors }: ReportCardProps) {
  const cardStyle = useAnimatedStyle(() => ({
    backgroundColor: interpolateColor(
      themeProgress.value,
      [0, 1],
      [LIGHT.surface, DARK.surface]
    ),
    borderColor: interpolateColor(
      themeProgress.value,
      [0, 1],
      [LIGHT.border, DARK.border]
    ),
  }));

  const titleStyle = useAnimatedStyle(() => ({
    color: interpolateColor(
      themeProgress.value,
      [0, 1],
      [LIGHT.text, DARK.text]
    ),
  }));

  const dateStyle = useAnimatedStyle(() => ({
    color: interpolateColor(
      themeProgress.value,
      [0, 1],
      [LIGHT.textMuted, DARK.textMuted]
    ),
  }));

  const dividerStyle = useAnimatedStyle(() => ({
    backgroundColor: interpolateColor(
      themeProgress.value,
      [0, 1],
      [LIGHT.border, DARK.border]
    ),
  }));

  return (
    <Animated.View style={[styles.reportCard, cardStyle]}>
      <View style={styles.reportHeader}>
        <View style={[styles.reportIconContainer, { backgroundColor: `${colors.primary}15` }]}>
          <Icon name="file-document-outline" size={24} color={colors.primary} />
        </View>
        <View style={styles.reportHeaderText}>
          <Animated.Text style={[styles.reportTitle, titleStyle]}>
            Dietary Analysis Report
          </Animated.Text>
          <Animated.Text style={[styles.reportDate, dateStyle]}>
            {report.periodLabel} • {new Date(report.createdAt).toLocaleDateString()}
          </Animated.Text>
        </View>
      </View>
      <Animated.View style={[styles.reportDivider, dividerStyle]} />
      <MarkdownRenderer text={report.report} colors={colors} themeProgress={themeProgress} />
    </Animated.View>
  );
}

interface DisclaimerBoxProps {
  themeProgress: Animated.SharedValue<number>;
  colors: any;
}

function DisclaimerBox({ themeProgress, colors }: DisclaimerBoxProps) {
  const textStyle = useAnimatedStyle(() => ({
    color: interpolateColor(
      themeProgress.value,
      [0, 1],
      [LIGHT.textMuted, DARK.textMuted]
    ),
  }));

  return (
    <View style={[styles.disclaimer, { backgroundColor: `${colors.warning}10` }]}>
      <Icon name="information-outline" size={18} color={colors.warning} />
      <Animated.Text style={[styles.disclaimerText, textStyle]}>
        This report is intended for clinical discussion, not diagnosis.
      </Animated.Text>
    </View>
  );
}

interface FooterButtonProps {
  onExport: () => void;
  exporting: boolean;
  themeProgress: Animated.SharedValue<number>;
  bottomInset?: number;
}

function FooterButton({ onExport, exporting, themeProgress, bottomInset = 0 }: FooterButtonProps) {
  const borderStyle = useAnimatedStyle(() => ({
    borderTopColor: interpolateColor(
      themeProgress.value,
      [0, 1],
      [LIGHT.border, DARK.border]
    ),
  }));

  return (
    <Animated.View style={[styles.footer, borderStyle, { paddingBottom: SPACING.lg + bottomInset }]}>
      <Button title="Export & Share PDF" onPress={onExport} loading={exporting} />
    </Animated.View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  safe: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SPACING.xxl,
    paddingTop: SPACING.lg,
    paddingBottom: SPACING.md,
    gap: SPACING.md,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerText: { flex: 1 },
  title: {
    fontFamily: TYPOGRAPHY.fontFamily.bold,
    fontSize: TYPOGRAPHY.sizes.headlineMedium,
  },
  subtitle: {
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    fontSize: TYPOGRAPHY.sizes.bodySmall,
    marginTop: 2,
  },
  scrollView: { flex: 1 },
  scrollContent: {
    paddingHorizontal: SPACING.xxl,
    paddingBottom: SPACING.xl,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    fontSize: TYPOGRAPHY.sizes.bodyMedium,
  },
  reportCard: {
    borderRadius: RADIUS.xl,
    padding: SPACING.xl,
    borderWidth: 1,
  },
  reportHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
  },
  reportIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportHeaderText: { flex: 1 },
  reportTitle: {
    fontFamily: TYPOGRAPHY.fontFamily.semiBold,
    fontSize: TYPOGRAPHY.sizes.headlineSmall,
  },
  reportDate: {
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    fontSize: TYPOGRAPHY.sizes.bodySmall,
    marginTop: 2,
  },
  reportDivider: {
    height: 1,
    marginVertical: SPACING.lg,
  },
  disclaimer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    marginTop: SPACING.lg,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
  },
  disclaimerText: {
    flex: 1,
    fontFamily: TYPOGRAPHY.fontFamily.regular,
    fontSize: TYPOGRAPHY.sizes.bodySmall,
  },
  footer: {
    padding: SPACING.xxl,
    paddingTop: SPACING.lg,
    borderTopWidth: 1,
  },
});
