import React from 'react';
import { View, ViewStyle } from 'react-native';
import {
  Settings,
  TrendingUp,
  FileText,
  History,
  Apple,
  Milk,
  Flame,
  Beef,
  Package,
  GlassWater,
  Coffee,
  Wine,
  UtensilsCrossed,
  Utensils,
  Wheat,
  Droplets,
  Citrus,
  Moon,
  PieChart,
  Activity,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Plus,
  Camera,
  CameraOff,
  X,
  Check,
  CheckCircle,
  AlertCircle,
  AlertTriangle,
  Clock,
  Calendar,
  CalendarDays,
  CalendarRange,
  Smartphone,
  Share2,
  Trash2,
  Edit3,
  Eye,
  EyeOff,
  Mail,
  Lock,
  User,
  LogOut,
  Bell,
  Sun,
  Palette,
  Upload,
  Download,
  Heart,
  HeartPulse,
  Sparkles,
  Zap,
  ShieldCheck,
  Loader2,
  Info,
  Brain,
  Stethoscope,
  Percent,
  Images,
  Image,
  type LucideIcon,
} from 'lucide-react-native';

// Map of icon names to Lucide components
const iconMap: Record<string, LucideIcon> = {
  // Navigation
  'settings': Settings,
  'cog-outline': Settings,
  'trending-up': TrendingUp,
  'chart-line': TrendingUp,
  'chart-line-variant': TrendingUp,
  'file-text': FileText,
  'file-document': FileText,
  'file-document-outline': FileText,
  'history': History,
  'apple': Apple,
  'food-apple': Apple,
  'food-apple-outline': Apple,

  // Food & Drink signals
  'bottle-soda': Milk,
  'pot-steam': Flame,
  'food-steak': Beef,
  'grill': Flame,
  'package-variant': Package,
  'cup': GlassWater,
  'coffee': Coffee,
  'glass-wine': Wine,
  'french-fries': UtensilsCrossed,
  'bread-slice': Wheat,
  'shaker': Droplets,
  'chili-hot': Flame,
  'fruit-citrus': Citrus,
  'weather-night': Moon,

  // Charts
  'chart-arc': PieChart,
  'chart-timeline-variant': Activity,
  'pie-chart': PieChart,
  'activity': Activity,

  // UI
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'plus': Plus,
  'camera': Camera,
  'camera-plus': Camera,
  'camera-off': CameraOff,
  'food': Utensils,
  'food-outline': Utensils,
  'utensils': Utensils,
  'utensils-crossed': UtensilsCrossed,
  'loader': Loader2,
  'loading': Loader2,
  'info': Info,
  'information': Info,
  'information-outline': Info,
  'alert': AlertTriangle,
  'alert-outline': AlertTriangle,
  'close': X,
  'x': X,
  'check': Check,
  'check-circle': CheckCircle,
  'alert-circle': AlertCircle,
  'alert-circle-outline': AlertCircle,
  'brain': Brain,
  'doctor': Stethoscope,
  'stethoscope': Stethoscope,
  'blood-bag': Droplets,
  'test-tube': Activity,
  'file-upload-outline': Upload,
  'pencil-outline': Edit3,
  'clock': Clock,
  'clock-outline': Clock,
  'calendar': Calendar,
  'calendar-week': CalendarDays,
  'calendar-month': CalendarDays,
  'calendar-range': CalendarRange,
  'cellphone': Smartphone,
  'moon-waning-crescent': Moon,
  'share': Share2,
  'share-variant': Share2,
  'trash': Trash2,
  'trash-can-outline': Trash2,
  'delete': Trash2,
  'delete-outline': Trash2,
  'edit': Edit3,
  'pencil': Edit3,
  'eye': Eye,
  'eye-outline': Eye,
  'eye-off': EyeOff,
  'eye-off-outline': EyeOff,
  'mail': Mail,
  'email': Mail,
  'email-outline': Mail,
  'lock': Lock,
  'lock-outline': Lock,
  'user': User,
  'account': User,
  'account-outline': User,
  'logout': LogOut,
  'bell': Bell,
  'bell-outline': Bell,
  'sun': Sun,
  'white-balance-sunny': Sun,
  'palette': Palette,
  'palette-outline': Palette,
  'upload': Upload,
  'download': Download,
  'heart': Heart,
  'heart-outline': Heart,
  'sparkles': Sparkles,
  'auto-fix': Sparkles,
  'zap': Zap,
  'lightning-bolt': Zap,
  'shield-check': ShieldCheck,
  'shield-check-outline': ShieldCheck,
  'shield-lock-outline': ShieldCheck,

  // Blood work icons
  'arrow-up-bold': ArrowUp,
  'arrow-down-bold': ArrowDown,
  'heart-pulse': HeartPulse,
  'glucose': Droplets,
  'water': Droplets,
  'percent': Percent,

  // Onboarding
  'meditation': Brain,

  // Gallery/Images
  'image': Image,
  'image-multiple': Images,
  'images': Images,
  'gallery': Images,
};

interface IconProps {
  name: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
  style?: ViewStyle;
}

export default function Icon({ name, size = 24, color = '#000', strokeWidth = 2, style }: IconProps) {
  const IconComponent = iconMap[name];

  if (!IconComponent) {
    console.warn(`Icon "${name}" not found in icon map`);
    return null;
  }

  if (style) {
    return (
      <View style={style}>
        <IconComponent size={size} color={color} strokeWidth={strokeWidth} />
      </View>
    );
  }

  return <IconComponent size={size} color={color} strokeWidth={strokeWidth} />;
}

// Export individual icons for direct imports
export {
  Settings,
  TrendingUp,
  FileText,
  History,
  Apple,
  Milk,
  Flame,
  Beef,
  Package,
  GlassWater,
  Coffee,
  Wine,
  UtensilsCrossed,
  Utensils,
  Wheat,
  Droplets,
  Citrus,
  Moon,
  PieChart,
  Activity,
  ChevronLeft,
  ChevronRight,
  ArrowLeft,
  ArrowRight,
  Plus,
  Camera,
  CameraOff,
  X,
  Check,
  CheckCircle,
  AlertCircle,
  AlertTriangle,
  Clock,
  Calendar,
  CalendarDays,
  CalendarRange,
  Smartphone,
  Share2,
  Trash2,
  Edit3,
  Eye,
  EyeOff,
  Mail,
  Lock,
  User,
  LogOut,
  Bell,
  Sun,
  Palette,
  Upload,
  Download,
  Heart,
  Sparkles,
  Zap,
  ShieldCheck,
  Loader2,
  Info,
  Brain,
  Stethoscope,
  Percent,
  HeartPulse,
  Images,
  Image,
};
